# Generated by Django 4.2.16 on 2024-09-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('PROJECT_MANAGER', 'Project Manager'), ('TEAM_MEMBER', 'Team Member')], default='TEAM_MEMBER', max_length=20),
        ),
    ]
