# Generated by Django 5.1.1 on 2024-10-04 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_billing_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="billing_status",
            new_name="billable_status",
        ),
    ]
