# Generated by Django 5.1.1 on 2024-10-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_task_attachments"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
